source-server:
  host: '${SOURCE_HOST:127.0.0.1}'
  port: '${SOURCE_PORT:1234}'

spring:
  application:
    name: client-server

server:
  address: '${CLIENT_HOST:127.0.0.1}'
  port: '${CLIENT_PORT:5678}'